# -*- coding: utf-8 -*-
"""(not chosen model: deepsort ).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xsAmecD8eIDBVcG4z369nvPPxDAuYXvx
"""

!pip install kagglehub --quiet


import kagglehub
import os

path1 = kagglehub.dataset_download("robikscube/driving-video-with-object-tracking")

path2 = kagglehub.dataset_download("deeplyft/driving-video-subset-50-with-object-tracking")

print("Dataset 1 path:", path1)
print(" Dataset 2 path:", path2)


video_extensions = ('.mp4', '.mov', '.avi')
all_videos = []

for dataset_path in [path1, path2]:
    for root, dirs, files in os.walk(dataset_path):
        for file in files:
            if file.lower().endswith(video_extensions):
                full_path = os.path.join(root, file)
                all_videos.append(full_path)

print(f"Total videos found: {len(all_videos)}")
print(" Example videos:", all_videos[:5])

!pip install kagglehub ultralytics deep-sort-realtime opencv-python --quiet

import cv2
from ultralytics import YOLO
from deep_sort_realtime.deepsort_tracker import DeepSort
import numpy as np

# Load YOLOv8 model (you can replace with a fine-tuned version)
model = YOLO("yolov8m.pt")

# Initialize DeepSORT tracker
tracker = DeepSort(max_age=30)

def detect_signal_color(frame, roi=None):
    """
    Detect if the traffic light in the ROI is red or green.
    roi: (x, y, w, h) region of interest
    """
    if roi is not None:
        x, y, w, h = roi
        frame = frame[y:y+h, x:x+w]

    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

    # HSV mask for red
    lower_red1 = np.array([0, 120, 70])
    upper_red1 = np.array([10, 255, 255])
    lower_red2 = np.array([170, 120, 70])
    upper_red2 = np.array([180, 255, 255])
    red_mask = cv2.bitwise_or(cv2.inRange(hsv, lower_red1, upper_red1),
                              cv2.inRange(hsv, lower_red2, upper_red2))

    # HSV mask for green
    lower_green = np.array([36, 50, 70])
    upper_green = np.array([89, 255, 255])
    green_mask = cv2.inRange(hsv, lower_green, upper_green)

    red_pixels = np.sum(red_mask > 0)
    green_pixels = np.sum(green_mask > 0)

    if red_pixels > green_pixels * 1.5:
        return "RED"
    elif green_pixels > red_pixels * 1.5:
        return "GREEN"
    else:
        return "UNKNOWN"

import os, cv2, random, csv, numpy as np
from collections import defaultdict, deque
from shapely.geometry import Point, Polygon
from ultralytics import YOLO
from IPython.display import Video, display
from deep_sort_realtime.deepsort_tracker import DeepSort

# ======================================
#  STEP 1: Load Video
# ======================================
VIDEO_FOLDER = "/kaggle/input/driving-video-with-object-tracking/bdd100k_videos_train_00/bdd100k/videos/train"

if not os.path.exists(VIDEO_FOLDER):
    raise FileNotFoundError("❌ Video folder not found!")

videos = [f for f in os.listdir(VIDEO_FOLDER) if f.lower().endswith(('.mp4', '.mov'))]
VIDEO_IN = os.path.join(VIDEO_FOLDER, random.choice(videos))
VIDEO_OUT = "deepsort_output.avi"

print(f"🎲 Selected video: {os.path.basename(VIDEO_IN)}")

cap = cv2.VideoCapture(VIDEO_IN)
fps = int(cap.get(cv2.CAP_PROP_FPS))
W, H = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)), int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
out = cv2.VideoWriter(VIDEO_OUT, cv2.VideoWriter_fourcc(*'XVID'), fps, (W, H))
print(f"🎥 Video loaded successfully ({W}x{H}, {fps} FPS)")

# ======================================
#  STEP 2: YOLOv8 + DeepSORT + Constants
# ======================================
model = YOLO("yolov8x.pt")
tracker = DeepSort(max_age=30)

VEHICLE_CLASSES = {"car", "truck", "bus", "motorbike", "motorcycle"}
SPEED_LIMIT_KMH = 80
LANE_CHANGE_IS_VIOLATION = True

# ======================================
#  STEP 3: Homography & Lanes
# ======================================
image_points = np.array([[250,700],[1050,700],[750,400],[550,400]],dtype=np.float32)
world_points = np.array([[0,0],[3.5,0],[3.5,30],[0,30]],dtype=np.float32)
H_matrix, _ = cv2.findHomography(image_points, world_points)

def pixel_to_world(x, y):
    p = np.array([[[x, y]]], np.float32)
    return cv2.perspectiveTransform(p, H_matrix)[0][0]

lane_right_poly = Polygon([(50,300),(600,300),(600,720),(50,720)])
lane_left_poly  = Polygon([(600,300),(1270,300),(1270,720),(600,720)])

def draw_lanes(frame):
    cv2.polylines(frame, [np.array(lane_right_poly.exterior.coords, np.int32)], True, (0,255,0), 2)
    cv2.polylines(frame, [np.array(lane_left_poly.exterior.coords, np.int32)], True, (255,0,0), 2)
    return frame

def point_in_lane(point, poly):
    return poly.contains(Point(point))

# ======================================
#  STEP 4: Memory & Counters
# ======================================
last_centers = {}
last_speed = {}
speeds_history = defaultdict(lambda: deque(maxlen=20))
lane_of_track = {}
viol_speed_ids = set()
viol_lane_ids = set()
frame_age = defaultdict(int)
records = []

# ======================================
# STEP 5: Main Loop
# ======================================
print("🚀 Starting detection & tracking with DeepSORT...")
frame_idx = 0

while True:
    ok, frame = cap.read()
    if not ok:
        break

    results = model(frame, conf=0.25, iou=0.45, imgsz=960, augment=True, verbose=False)[0]

    detections = []
    for box, cls, conf in zip(results.boxes.xyxy, results.boxes.cls, results.boxes.conf):
        label = model.model.names[int(cls)]
        if label in VEHICLE_CLASSES:
            detections.append(([int(box[0]), int(box[1]), int(box[2])-int(box[0]), int(box[3])-int(box[1])], conf.item(), label))

    tracks = tracker.update_tracks(detections, frame=frame)
    frame = draw_lanes(frame)

    for t in tracks:
        if not t.is_confirmed(): continue
        tid = t.track_id
        x1, y1, x2, y2 = map(int, t.to_ltrb())
        cx, cy = (x1 + x2)//2, (y1 + y2)//2
        center = (cx, cy)
        label = t.det_class or "vehicle"
        frame_age[tid] += 1

        # Lane checking
        in_right = point_in_lane(center, lane_right_poly)
        in_left = point_in_lane(center, lane_left_poly)
        curr_lane = "R" if in_right else ("L" if in_left else "U")
        prev_lane = lane_of_track.get(tid, curr_lane)
        lane_of_track[tid] = curr_lane
        if LANE_CHANGE_IS_VIOLATION and curr_lane != prev_lane and prev_lane in ("L","R") and curr_lane in ("L","R"):
            viol_lane_ids.add(tid)

        # Speed calculation
        if tid in last_centers:
            prev_world = pixel_to_world(*last_centers[tid])
            curr_world = pixel_to_world(cx, cy)
            dist_m = np.linalg.norm(np.array(curr_world) - np.array(prev_world))
            if 0.2 < dist_m < 10:
                speed_kmh = dist_m * fps * 3.6
                last_s = last_speed.get(tid, 0)
                if abs(speed_kmh - last_s) > 40:
                    speed_kmh = last_s
                speeds_history[tid].append(speed_kmh)
                avg_speed = np.mean(speeds_history[tid])
                last_speed[tid] = speed_kmh
            else:
                avg_speed = 0
        else:
            avg_speed = 0.0

        last_centers[tid] = center

        # Violations
        violation_type = "None"
        color = (0,255,0)
        top_label = f"ID {tid}"

        if avg_speed < 8:
            avg_speed = 0
        elif frame_age[tid] > 5 and avg_speed > SPEED_LIMIT_KMH:
            viol_speed_ids.add(tid)
            color = (0,0,255)
            top_label = f" SPEED VIOLATION (ID {tid})"
            violation_type = "Speed"
        elif tid in viol_lane_ids:
            color = (255,0,0)
            top_label = f" LANE VIOLATION (ID {tid})"
            violation_type = "Lane"

        # Draw on frame
        cv2.rectangle(frame, (x1,y1), (x2,y2), color, 2)
        cv2.putText(frame, top_label, (x1, max(20, y1 - 25)), cv2.FONT_HERSHEY_SIMPLEX, 0.7, color, 2)
        cv2.putText(frame, f"{label} | {avg_speed:.1f} km/h", (x1, y2 + 25),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)

        # Save record
        records.append({
            "Frame": frame_idx,
            "TrackID": tid,
            "Vehicle": label,
            "Speed (km/h)": round(avg_speed, 2),
            "Violation": violation_type,
            "Lane": curr_lane
        })

    out.write(frame)
    frame_idx += 1
    if frame_idx % 50 == 0:
        print(f" Processed {frame_idx} frames")

cap.release()
out.release()
print(f" Done! Total frames: {frame_idx}")

# ======================================
#  Smart Accuracy Evaluation
# ======================================

import numpy as np

total_vehicles = len(speeds_history)
valid_tracks = 0
stable_tracks = 0
smooth_tracks = 0
logical_tracks = 0
track_mean_speeds = []

for tid, speeds in speeds_history.items():
    speeds = np.array(list(speeds))
    if len(speeds) < 5:
        continue
    valid_tracks += 1

    std_speed = np.std(speeds)
    if std_speed < 8:
        stable_tracks += 1
    if np.all(np.diff(speeds) < 30):
        smooth_tracks += 1
    if np.all((speeds >= 0) & (speeds <= 180)):
        logical_tracks += 1

    track_mean_speeds.append(np.mean(speeds))

if valid_tracks > 0:
    stability_score = stable_tracks / valid_tracks
    smoothness_score = smooth_tracks / valid_tracks
    logic_score = logical_tracks / valid_tracks
    movement_score = sum(np.array(track_mean_speeds) > 3) / valid_tracks

    accuracy = (0.35*stability_score +
                0.35*smoothness_score +
                0.2*movement_score +
                0.1*logic_score)
else:
    accuracy = 0

print("\nSMART VIDEO ACCURACY REPORT")
print("===============================================")
print(f" Vehicles Tracked     : {total_vehicles}")
print(f" Valid Tracks         : {valid_tracks}")
print(f" Speed Stability      : {stability_score*100:.2f}%")
print(f" Speed Smoothness     : {smoothness_score*100:.2f}%")
print(f" Active Movement      : {movement_score*100:.2f}%")
print(f" Logical Speed Ranges : {logic_score*100:.2f}%")
print("-----------------------------------------------")
print(f" Estimated Accuracy    : {accuracy*100:.2f}%")
print("===============================================")

# ======================================
#  CSV Report + Video Output
# ======================================

import pandas as pd
import subprocess

report_rows = []
for tid, speeds in speeds_history.items():
    if not speeds:
        continue
    vehicle_type = "car"
    avg_speed = np.mean(speeds)
    speed_violation = "Yes" if tid in viol_speed_ids else "No"
    lane_violation = "Yes" if tid in viol_lane_ids else "No"

    report_rows.append({
        "ID": tid,
        "Vehicle": vehicle_type,
        "Avg_Speed (km/h)": round(avg_speed, 2),
        "Speed_Violation": speed_violation,
        "Lane_Violation": lane_violation
    })

report_df = pd.DataFrame(report_rows)
csv_path = "deepsort_traffic_report.csv"
report_df.to_csv(csv_path, index=False)

print("\n Summary Report:")
print("=================================================")
print(f" Total Vehicles Detected : {len(report_df)}")
print(f" Speed Violations         : {sum(report_df['Speed_Violation'] == 'Yes')}")
print(f" Lane Violations          : {sum(report_df['Lane_Violation'] == 'Yes')}")
print(f" CSV saved as: {csv_path}")
print("=================================================")

# 🎬 Convert AVI → MP4
subprocess.run(["ffmpeg", "-y", "-i", "deepsort_output.avi",
                "-c:v", "libx264", "-pix_fmt", "yuv420p",
                "deepsort_final_output.mp4", "-loglevel", "quiet"])

display(Video("deepsort_final_output.mp4", width=720, embed=True))

# ======================================
#  Download Sample Traffic Video (Direct URL)
# ======================================

import urllib.request
from IPython.display import Video, display

# ✅ Fixed working traffic video link
url = "https://github.com/karimkhanp/traffic-detection-yolo/raw/main/sample_video.mp4"
video_path = "traffic_video.mp4"

print("⬇️ Downloading sample traffic video...")
urllib.request.urlretrieve(url, video_path)
print(f"✅ Download complete! Saved as: {video_path}")

# 🎦 Display the downloaded video
display(Video(video_path, width=720))