# -*- coding: utf-8 -*-
"""chosen_model_(byte_track).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pG7Dk8nnbGPwWN9gmqrPU_ykX2hGoZUV
"""

!pip install -U kagglehub supervision shapely ultralytics --quiet

import cv2, random, numpy as np, pandas as pd
from shapely.geometry import Point, Polygon
from collections import defaultdict, deque
from ultralytics import YOLO
import supervision as sv
from IPython.display import Video, display

import kagglehub, os
path = kagglehub.dataset_download("robikscube/driving-video-with-object-tracking")
print("✅ Dataset Path:", path)

# Locate video folder
for root, dirs, files in os.walk(path):
    videos = [f for f in files if f.lower().endswith(('.mp4', '.mov', '.avi'))]
    if videos:
        VIDEO_FOLDER = root
        break

print(f"🎥 Found video folder: {VIDEO_FOLDER}")

import os, cv2, random, csv, numpy as np
from collections import defaultdict, deque
from shapely.geometry import Point, Polygon
import supervision as sv
from ultralytics import YOLO
from IPython.display import Video, display

# ======================================
#  STEP 1: Load Video
# ======================================
VIDEO_FOLDER = "/kaggle/input/driving-video-with-object-tracking/bdd100k_videos_train_00/bdd100k/videos/train"

if not os.path.exists(VIDEO_FOLDER):
    raise FileNotFoundError(" Video folder not found!")

videos = [f for f in os.listdir(VIDEO_FOLDER) if f.lower().endswith(('.mp4', '.mov'))]
VIDEO_IN = os.path.join(VIDEO_FOLDER, random.choice(videos))
VIDEO_OUT = "enhanced_output.avi"

print(f"🎲 Selected video: {os.path.basename(VIDEO_IN)}")

cap = cv2.VideoCapture(VIDEO_IN)
fps = int(cap.get(cv2.CAP_PROP_FPS))
W, H = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)), int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
out = cv2.VideoWriter(VIDEO_OUT, cv2.VideoWriter_fourcc(*'XVID'), fps, (W, H))
print(f" Video loaded successfully ({W}x{H}, {fps} FPS)")

# ======================================
#  STEP 2: YOLOv8 + Tracker + Constants
# ======================================
model = YOLO("yolov8x.pt")
tracker = sv.ByteTrack()

VEHICLE_CLASSES = {"car", "truck", "bus", "motorbike", "motorcycle"}
SPEED_LIMIT_KMH = 80
LANE_CHANGE_IS_VIOLATION = True

# ======================================
#  STEP 3: Homography & Lanes
# ======================================
image_points = np.array([[250,700],[1050,700],[750,400],[550,400]],dtype=np.float32)
world_points = np.array([[0,0],[3.5,0],[3.5,30],[0,30]],dtype=np.float32)
H_matrix, _ = cv2.findHomography(image_points, world_points)

def pixel_to_world(x, y):
    p = np.array([[[x, y]]], np.float32)
    return cv2.perspectiveTransform(p, H_matrix)[0][0]

lane_right_poly = Polygon([(50,300),(600,300),(600,720),(50,720)])
lane_left_poly  = Polygon([(600,300),(1270,300),(1270,720),(600,720)])

def draw_lanes(frame):
    cv2.polylines(frame, [np.array(lane_right_poly.exterior.coords, np.int32)], True, (0,255,0), 2)
    cv2.polylines(frame, [np.array(lane_left_poly.exterior.coords, np.int32)], True, (255,0,0), 2)
    return frame

def point_in_lane(point, poly):
    return poly.contains(Point(point))

# ======================================
#  STEP 4: Memory & Counters
# ======================================
last_centers = {}
last_speed = {}
speeds_history = defaultdict(lambda: deque(maxlen=20))
lane_of_track = {}
viol_speed_ids = set()
viol_lane_ids = set()
frame_age = defaultdict(int)
records = []

# ======================================
# 🚗 STEP 5: Main Loop
# ======================================
print(" Starting detection & tracking...")
frame_idx = 0

while True:
    ok, frame = cap.read()
    if not ok:
        break

    results = model(frame, conf=0.25, iou=0.45, imgsz=960, augment=True, verbose=False)[0]
    detections = sv.Detections.from_ultralytics(results)
    tracked = tracker.update_with_detections(detections)
    frame = draw_lanes(frame)

    for i in range(len(tracked.xyxy)):
        box = tracked.xyxy[i]
        cls = tracked.class_id[i]
        tid = tracked.tracker_id[i]
        if tid is None: continue

        label = model.model.names[int(cls)]
        if label not in VEHICLE_CLASSES: continue

        x1, y1, x2, y2 = map(int, box)
        cx, cy = (x1 + x2)//2, (y1 + y2)//2
        center = (cx, cy)
        frame_age[tid] += 1

        # Lane checking
        in_right = point_in_lane(center, lane_right_poly)
        in_left = point_in_lane(center, lane_left_poly)
        curr_lane = "R" if in_right else ("L" if in_left else "U")
        prev_lane = lane_of_track.get(tid, curr_lane)
        lane_of_track[tid] = curr_lane

        if LANE_CHANGE_IS_VIOLATION and curr_lane != prev_lane and prev_lane in ("L","R") and curr_lane in ("L","R"):
            viol_lane_ids.add(tid)

        # Speed calculation
        if tid in last_centers:
            prev_world = pixel_to_world(*last_centers[tid])
            curr_world = pixel_to_world(cx, cy)
            dist_m = np.linalg.norm(np.array(curr_world) - np.array(prev_world))
            if 0.2 < dist_m < 10:
                speed_kmh = dist_m * fps * 3.6
                last_s = last_speed.get(tid, 0)
                if abs(speed_kmh - last_s) > 40:
                    speed_kmh = last_s
                speeds_history[tid].append(speed_kmh)
                avg_speed = np.mean(speeds_history[tid])
                last_speed[tid] = speed_kmh
            else:
                avg_speed = 0
        else:
            avg_speed = 0.0

        last_centers[tid] = center

        # Violations
        violation_type = "None"
        color = (0,255,0)
        top_label = f"ID {tid}"

        if avg_speed < 8:
            avg_speed = 0
        elif frame_age[tid] > 5 and avg_speed > SPEED_LIMIT_KMH:
            viol_speed_ids.add(tid)
            color = (0,0,255)
            top_label = f" SPEED VIOLATION (ID {tid})"
            violation_type = "Speed"
        elif tid in viol_lane_ids:
            color = (255,0,0)
            top_label = f" LANE VIOLATION (ID {tid})"
            violation_type = "Lane"

        # Draw on frame
        cv2.rectangle(frame, (x1,y1), (x2,y2), color, 2)
        cv2.putText(frame, top_label, (x1, max(20, y1 - 25)), cv2.FONT_HERSHEY_SIMPLEX, 0.7, color, 2)
        cv2.putText(frame, f"{label} | {avg_speed:.1f} km/h", (x1, y2 + 25),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)

        # Save record for CSV
        records.append({
            "Frame": frame_idx,
            "TrackID": tid,
            "Vehicle": label,
            "Speed (km/h)": round(avg_speed, 2),
            "Violation": violation_type,
            "Lane": curr_lane
        })

    out.write(frame)
    frame_idx += 1
    if frame_idx % 50 == 0:
        print(f" Processed {frame_idx} frames")

cap.release()
out.release()
print(f" Done! Total frames: {frame_idx}")

# ======================================
# 📊 STEP 6: Save CSV Report
# ======================================
csv_filename = "traffic_violations_report.csv"
with open(csv_filename, "w", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=["Frame","TrackID","Vehicle","Speed (km/h)","Violation","Lane"])
    writer.writeheader()
    writer.writerows(records)
print(f"📄 CSV report saved as {csv_filename} ({len(records)} records)")

# ======================================
# 🎬 STEP 7: Display Final Video
# ======================================
print("⚙️ Re-encoding for Colab playback...")
!ffmpeg -y -i enhanced_output.avi -c:v libx264 -pix_fmt yuv420p final_violation_output.mp4 -loglevel quiet
print("✅ Re-encoded successfully!")
display(Video("final_violation_output.mp4", width=720, embed=True))

from google.colab import files

files.download("final_violation_output.mp4")

import numpy as np

# Calculate the number of vehicles
total_vehicles = len(speeds_history)
valid_tracks = 0
stable_tracks = 0
smooth_tracks = 0
logical_tracks = 0
track_mean_speeds = [] # List to store mean speeds of each track

for tid, speeds in speeds_history.items():
    speeds = np.array(list(speeds)) # Convert deque to numpy array
    if len(speeds) < 5:
        continue
    valid_tracks += 1

    # Speed stability
    std_speed = np.std(speeds)
    if std_speed < 8:
        stable_tracks += 1

    # Speed smoothness
    if np.all(np.diff(speeds) < 30):
        smooth_tracks += 1

    # Logical speeds
    if np.all((speeds >= 0) & (speeds <= 180)):
        logical_tracks += 1

    # Store the mean speed of this track
    track_mean_speeds.append(np.mean(speeds))


if valid_tracks > 0:
    stability_score = stable_tracks / valid_tracks
    smoothness_score = smooth_tracks / valid_tracks
    logic_score = logical_tracks / valid_tracks
    # Calculate the average movement score from the list of mean speeds
    movement_score = sum(np.array(track_mean_speeds) > 3) / valid_tracks


    # Final score (balanced)
    accuracy = (0.35*stability_score +
                0.35*smoothness_score +
                0.2*movement_score +
                0.1*logic_score)
else:
    accuracy = 0

print("\n📊 SMART VIDEO ACCURACY REPORT")
print("===============================================")
print(f"🚗 Vehicles Tracked     : {total_vehicles}")
print(f"✅ Valid Tracks         : {valid_tracks}")
print(f"📉 Speed Stability      : {stability_score*100:.2f}%")
print(f"🌀 Speed Smoothness     : {smoothness_score*100:.2f}%")
print(f"🏃 Active Movement      : {movement_score*100:.2f}%")
print(f"🧠 Logical Speed Ranges : {logic_score*100:.2f}%")
print("-----------------------------------------------")
print(f"🎯 Estimated Accuracy    : {accuracy*100:.2f}%")
print("===============================================")

# ======================================
# 📊 STEP 6: Generate CSV Summary Report
# ======================================

import pandas as pd

# Prepare a list for report rows
report_rows = []

for tid, speeds in speeds_history.items():
    if not speeds:
        continue

    vehicle_type = "car"  # default; you can enhance by storing actual class per tid
    avg_speed = np.mean(speeds)
    speed_violation = "Yes" if tid in viol_speed_ids else "No"
    lane_violation = "Yes" if tid in viol_lane_ids else "No"

    report_rows.append({
        "ID": tid,
        "Vehicle": vehicle_type,
        "Avg_Speed (km/h)": round(avg_speed, 2),
        "Speed_Violation": speed_violation,
        "Lane_Violation": lane_violation
    })

# Convert to DataFrame
report_df = pd.DataFrame(report_rows)

# Save CSV
csv_path = "traffic_violations_report.csv"
report_df.to_csv(csv_path, index=False)

# --- Summary statistics ---
total_vehicles = len(report_df)
speed_violations = sum(report_df["Speed_Violation"] == "Yes")
lane_violations = sum(report_df["Lane_Violation"] == "Yes")
avg_overall_speed = report_df["Avg_Speed (km/h)"].mean() if not report_df.empty else 0

# Print summary
print("\n📋 Summary Report:")
print("=================================================")
print(f"🚗 Total Vehicles Detected : {total_vehicles}")
print(f"⚡ Speed Violations         : {speed_violations}")
print(f"↔ Lane Violations          : {lane_violations}")

print("=================================================")
print(f"✅ CSV report saved as: {csv_path}")
display(report_df.head(10))